### ISSUE TITLE
Work on improving events page css.

### ISSUE THREAD

**Issue by Aniket21mathur** [alumnicelliitr/Raionzo-website#41]
![image](https://user-images.githubusercontent.com/35092582/60665106-30e82200-9e81-11e9-8277-726f41c7f3fc.png)

**Comment by Aniket21mathur** [comment]
@NitinBhasneia start working on this. :-)

**Comment by NitinBhasneia** [comment]
Done

**Comment by Aniket21mathur** [comment]
Still some scope of improvement. :-)
